### ISSUE TITLE
Cordova encountered an error

### ISSUE THREAD

**Issue by bostrot** [blocktrail/blocktrail-wallet#36]
This is what I get when I try to run this: `ionic cordova run android`	

	(node:7724) DeprecationWarning: util.puts is deprecated. Use console.log instead.
	events.js:160
		  throw er; // Unhandled 'error' event
		  ^

	TypeError: Cannot read property 'toString' of null
		at Object.localAddrs (C:\Users\errec\Documents\GitHub\blocktrail-wallet\hooks\utils.js:48:28)
		at C:\Users\errec\Documents\GitHub\blocktrail-wallet\hooks\before_prepare\020_modify_config.js:25:37
		at Parser.<anonymous> (C:\Users\errec\Documents\GitHub\blocktrail-wallet\node_modules\xml2js\lib\xml2js.js:489:18)
		at emitOne (events.js:96:13)
		at Parser.emit (events.js:188:7)
		at Object.onclosetag (C:\Users\errec\Documents\GitHub\blocktrail-wallet\node_modules\xml2js\lib\xml2js.js:447:26)
		at emit (C:\Users\errec\Documents\GitHub\blocktrail-wallet\node_modules\sax\lib\sax.js:639:35)
		at emitNode (C:\Users\errec\Documents\GitHub\blocktrail-wallet\node_modules\sax\lib\sax.js:644:5)
		at closeTag (C:\Users\errec\Documents\GitHub\blocktrail-wallet\node_modules\sax\lib\sax.js:903:7)
		at Object.write (C:\Users\errec\Documents\GitHub\blocktrail-wallet\node_modules\sax\lib\sax.js:1436:13)
	Error: Hook failed with error code 1: C:\Users\errec\Documents\GitHub\blocktrail-wallet\hooks\before_prepare\020_modify_
	config.js

	[ERROR] Cordova encountered an error.
			You may get more insight by running the Cordova command above directly.

	[ERROR] An error occurred while running cordova run android (exit code 1).

How can I resolve this?

**Comment by lacksfish** [comment]
Can you try running `ionic run android` instead? What's the output?

**Comment by lacksfish** [comment]
Closing this due to inactivity, if the issue is still persistent please feel free to open another issue and possibly link to this one (#36).

Make sure to include information like node version, gulp version, ionic version.
